apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dev-data-efs-pv
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    version: {{ .Chart.Version }}
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    # Create this first!
    server: {{ .Values.mysqlStorage.efs.server }}
    path: "/mysql-dev-data"